version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"   # SMTP server port
      - "8025:8025"   # Web UI port
