version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8080:80"
    environment:
      - WEBSOCKET_ENABLED=true  # Habilita WebSockets (melhor performance)
      - SIGNUPS_ALLOWED=false  # Define como "true" se quiser permitir novos cadastros
      - ADMIN_TOKEN=supersecreto  # Substitua por uma senha forte para acesso ao painel admin
