version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - LOG_LEVEL=INFO  # Define o nível de log - LOG_LEVEL=INFO  # Define o nível de log
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - keycloak_network
    command:
      - start-dev
      - --import-realm
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.1.100:12201"  # Substitua pelo IP ou hostname do seu servidor Seq
        tag: "keycloak"

volumes:
  keycloak_data:

networks:
  keycloak_network:
    driver: bridge
