version: '3.8'

services:
  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_password
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=moodle_user
      - MARIADB_PASSWORD=moodle_password
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:
