version: '3'

services:
  asterisk:
    image: inivirtual/asterisk
    container_name: asterisk
    ports:
      - "5060:5060/udp"  # Porta SIP
      - "5060:5060/tcp"
      - "10000-20000:10000-20000/udp"  # Portas RTP para chamadas de voz
    volumes:
      - ./asterisk-config:/etc/asterisk
    environment:
      - ASTERISK_DAEMON=1
    restart: always
