version: '3'
services:
  asterisk:
    # image: andrius/asterisk
    image: andrius/asterisk
    container_name: asterisk
    ports:
      - "5060:5060/udp"      # Porta SIP
      - "10000-20000:10000-20000/udp"  # RTP para áudio
    volumes:
      - ./asterisk_conf:/etc/asterisk
    networks:
      - voipnet

networks:
  voipnet:
    driver: bridge
