version: '3.8'

services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    ports:
      - "3000:3000"  # Porta da API WAHA
    environment:
      - WAHA_ENGINE=WEBJS
      - WAHA_SESSION_DIR=/sessions
      - WAHA_WEBHOOK_URL=http://host.docker.internal:5000/webhook  # URL do seu backend no host
      - WAHA_WEBHOOK_EVENTS=all
    volumes:
      - ./sessions:/sessions
    restart: unless-stopped
