version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9009:9009"   # API compatível com S3
      - "9008:9008"   # Painel web do MinIO
    environment:
      MINIO_ROOT_USER: admin         # Usuário de admin
      MINIO_ROOT_PASSWORD: admin123  # Senha de admin (mude para produção)
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9008"

volumes:
  minio_data:
